apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordcount-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordcount
  template:
    metadata:
      labels:
        app: wordcount
    spec:
      containers:
      - name: wordcount-container
        image: wordcount:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data-volume
          mountPath: "/data"
      volumes:
      - name: data-volume
        hostPath:
          path: /mnt/data
---
apiVersion: v1
kind: Service
metadata:
  name: wordcount-service
spec:
  selector:
    app: wordcount
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
